# ============================
# BASIC SITE SETTINGS
# ============================
remote_theme: "mmistakes/so-simple-theme"
include: ["_data"]
navigation: true
skin: "/assets/css/skins/default.css"
locale: en-US

title: "Build Fun Stuff"
description: "Coding & DIY Stuff"

# When using a custom domain:u
url: "https://build.kervian.com"
baseurl: ""

# Optional logo (leave blank if none)
logo:

# Date format for posts
date_format: "%B %-d, %Y"

# Estimated reading time for posts
read_time: false

# Google Fonts used by So Simple
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Disable analytics and comments for now
google_analytics:
disqus:
  shortname:

# ============================
# BUILD SETTINGS
# ============================

permalink: /:title/
markdown: kramdown

feed:
  path: atom.xml

search_full_content: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# ============================
# DEFAULT FRONT MATTER
# ============================

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false

# ============================
# AUTHOR (kept empty)
# ============================
author:
  links: false
# ============================
# FOOTER LINKS
# ============================

footer_links: false
